### PR TITLE
fix: chain & contract manual interaction

### LINKED ISSUE #710: `pop call contract` not working properly
Calling this command

```bash
pop call contract \
-p ./ \
-u wss://testnet-passet-hub.polkadot.io \
--contract 0x4ea5394ad19589052f7803f45ae4caa3041485b9 \
-s 0xfa273dfe0ffd0e021804b2616c4b2d61eff091f2cdd4f57c065d1b262a434fac \
--message swap_pas_to_usdc --args 10000000000 1000000 5DFYUxHHuEAcHQX4qZr3WoZhAqbEZoDFqUgbQuT9P5A9iDci -x
```
on this contract https://github.com/r0gue-io/symbiosis-contract-examples/tree/main/swap_pas_for_usdc prompts the user about the args, even tho they are specified on the command.

Additionally, all calls that attempt to modify the state prompts the user about the gas estimation if the `--dev` flag isn't used. 

This is blocking the use of this command in CIs and AI integrations, which is a special pain in the ass for the coming sub0

### PR DESCRIPTION
**Pull request by Daanvdplas**
Closes #710

### CODE REVIEW

File: crates/pop-cli/src/commands/call/contract.rs [hunk 1]
```diff
@@ -52,12 +51,24 @@ pub struct CallContractCommand {
...
 	/// If not specified it will perform a dry-run to estimate the gas consumed for the
 	/// call.
-	#[arg(name = "gas", short, long)]
+	/// DEPRECATED use `--manual-weight <REF_TIME> <PROOF_SIZE>` instead, removed in v0.13.0.
+	#[arg(name = "gas", short, long, conflicts_with = "manual_weight", requires = "proof_size")]
 	gas_limit: Option<u64>,
 	/// Maximum proof size for this command.
 	/// If not specified it will perform a dry-run to estimate the proof size required.
-	#[arg(short = 'P', long)]
+	/// DEPRECATED use `--manual-weight <REF_TIME> <PROOF_SIZE>` instead, will be removed in
```
Comment (Daanvdplas) [inline crates/pop-cli/src/commands/call/contract.rs]:
```suggestion
	#[deprecated(since = "0.12.0", note = "use `--manual-weight <REF_TIME> <PROOF_SIZE>` instead, will be removed in v0.13.0")]
```

File: crates/pop-cli/src/commands/call/contract.rs [hunk 2]
```diff
@@ -85,11 +96,15 @@ pub struct CallContractCommand {
 	dry_run: bool,
 	/// Enables developer mode, bypassing certain user prompts for faster testing.
 	/// Recommended for testing and local development only.
-	#[arg(name = "dev", short, long, default_value = "false")]
+	/// DEPRECATED Use `--skip-confirm` and/or `--manual-weight`, will be removed in v0.13.0.
```
Comment (Daanvdplas) [inline crates/pop-cli/src/commands/call/contract.rs]:
```suggestion
	/// DEPRECATED Use `--skip-confirm` and/or `--manual-weight`, will be removed in v0.13.0.
	#[deprecated(since = "0.12.0", note = "Use `--skip-confirm` and/or `--manual-weight`, will be removed in v0.13.0")]
```
